---
# This role installs httpd

- name: Install http
  become: yes
  become_method: sudo
  yum: name={{ item }} state=present
  with_items:
   - httpd

- name: http service state
  become: yes
  become_method: sudo
  service: name=httpd state=started enabled=yes
