---
# Handlers for web

- name: restart firewalld
  become: yes
  become_method: sudo
  service: name=firewalld state=restarted

- name: restart httpd
  become: yes
  become_method: sudo
  service: name=httpd state=restarted
