---
# Handlers for HAproxy

- name: restart haproxy
  become: yes
  become_method: sudo
  service: name=haproxy state=restarted

- name: reload haproxy
  become: yes
  become_method: sudo
  service: name=haproxy state=reloaded

- name: restart firewalld
  become: yes
  become_method: sudo
  service: name=firewalld state=restarted
