---
# This role contains common plays that will run on all nodes.

- name: Install python bindings for SE Linux
  become: yes
  become_method: sudo
  yum: name={{ item }} state=present
  with_items:
   - libselinux-python
   - libsemanage-python

- name: Create the repository for EPEL
  become: yes
  become_method: sudo
  copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo

- name: Create the GPG key for EPEL
  become: yes
  become_method: sudo
  copy: src=RPM-GPG-KEY-EPEL-7 dest=/etc/pki/rpm-gpg

#- name: install some useful nagios plugins
#  yum: name={{ item }} state=present
#  with_items:
#   - nagios-nrpe
#   - nagios-plugins-swap
#   - nagios-plugins-users
#   - nagios-plugins-procs
#   - nagios-plugins-load
#   - nagios-plugins-disk

#- name: Install ntp
#  become: yes
#  become_method: sudo
#  yum: name=ntp state=present
#  tags: ntp

#- name: Configure ntp file
#  become: yes
#  become_method: sudo
#  template: src=ntp.conf.j2 dest=/etc/ntp.conf
#  tags: ntp
#  notify: restart ntp

#- name: Start the ntp service
#  become: yes
#  become_method: sudo
#  service: name=ntpd state=started enabled=yes
#  tags: ntp

## work around RHEL 7, for now
#- name: insert iptables template
#  become: yes
#  become_method: sudo
#  template: src=iptables.j2 dest=/etc/sysconfig/iptables
#  when: ansible_distribution_major_version != '7'
#  notify: restart iptables

- name: test to see if selinux is running
  become: yes
  become_method: sudo
  command: getenforce
  register: sestatus
  changed_when: false
